import type { Metadata } from "next";
import { Geist, Geist_Mono, Bricolage_Grotesque, Literata } from "next/font/google";
import { ClerkProvider } from '@clerk/nextjs';
import "./globals.css";
import "./scroll.css"


export const bricolage = Bricolage_Grotesque({
  variable: "--font-bricolage-grotesque",
  subsets: ['latin'],
});

export const literata = Literata({
  subsets: ["latin"],
  weight: ["300"],
  variable: "--font-literata",
  display: "swap",
  fallback: ["serif"],
  preload: true,
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body
          className={`font-sans ${literata.variable} antialiased`}
        >
          {children}
        </body>
      </html>
    </ClerkProvider>
  );
}
